### ISSUE TITLE
Clean up the class and rebuild the post editor UI

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#348]
## Notes for testers

**What we expect**
Our metabox Social Warfare, in the post editor, has a makeover.

**How to Test**

1. Create a new post. Find the Social Warfare metabox. 
2. Find the Open Graph section. For each Open Graph image/input, update it with new content. Press save changes. 
3. Browse around for a couple pages, then return to the same post editor. The new images/content should be the exact same. 
4. Repeat steps 2-3 for the Twitter, Pinterest, and Other Options sections.

If something does not go as described above, please let us know in the comments. 
Once you have finished testing, please give this comment a thumbs up. 

### end notes
Step 1: Rebuild the metabox fields to use our own proprietary functions rather than relying on the metabox class from Rylwis.

Step 2: Restyle the metabox fields to visually look and behave the way the specs from @DustinWStout has drawn up. (These specs will be posted below).

- [ ] Build the parent class into core so that it can be easily extended using pro or other addons.
- [ ] Ensure the new system stores and retrieves data from the db in the same way as the existing system so previously set options are not lost.
- [ ] Style the elements to match designs submitted by Dustin below in this thread.

**Comment by DustinWStout** [comment]
<img width="675" alt="tab-1-social-open-graph" src="https://cloud.githubusercontent.com/assets/2152604/23817910/bcf53a10-05ab-11e7-94f6-003c4ae268da.png">
<img width="675" alt="tab-2-pinterest" src="https://cloud.githubusercontent.com/assets/2152604/23817911/bd0784d6-05ab-11e7-874d-1227ca39a205.png">
<img width="673" alt="tab-3-twitter" src="https://cloud.githubusercontent.com/assets/2152604/23817912/bd14b796-05ab-11e7-9614-6e2f75a3e9b8.png">
<img width="673" alt="tab-4-other-settings" src="https://cloud.githubusercontent.com/assets/2152604/23817913/bd173a66-05ab-11e7-9fab-00f835a3a0e8.png">

**Comment by Nicholas-Cardot** [comment]
**Developer Guidance**

We're going to do this project in 2 phases.

**Phase 1:** Rebuild the post editor custom option to act and behave exactly as they already do. In this phase, the goal is to simply break it away from the third-party metabox plugin that we are using.

**Phase 2:** Once we have it completely proprietary, then we will work on restyling it into the tabbed interface seen in the screenshots above.

**Important:** Our proprietary version MUST store all data in the same fields and in the same format that the current system is using so that all data entered prior to this update will work seemlessly with the new  system.

**Comment by scott-wiser** [comment]
I'll start inspecting the existing code and planning the rebuilding

**Comment by DustinWStout** [comment]
Here's the updated design guys: 

![all post options compact columns](https://user-images.githubusercontent.com/2152604/35994059-13570396-0cc4-11e8-9d6f-af31cba9f8e2.png)

**Comment by ckmahoney** [comment]
This issue was created over a year ago. Which parts of this are pertinent to 3.3.0 (is the content of the first two comments applicable to today?) @Nicholas-Cardot

**Comment by Nicholas-Cardot** [comment]
This is pretty much all still relevant. Right now we use a third party class to generate all of those custom fields. We can still use that, but I want to do a few things. 

First, strip out all parts of the class that we aren't using. It comes with like 35 different fields types. We're only using a few of them.

Second, let's make it fully Gutenberg compatible.

Third, let's move it into core so pro and other addons can add fields to it.

Fourth, let's restyle it to look like the last sketch that Dustin posted above.

**Comment by ckmahoney** [comment]
Many commits on Sept 4 referenced part 1 of this issue.

**Comment by DustinWStout** [comment]
Looks great... I have a few changes though: 

- [ ] Change recommended Pinterest image size to 600x900 (or 1000x1500)
- [ ] change `p.description` margin to `15px 0;`
- [ ] give `.wp-core-ui #social_warfare a.swpmb-add-media.button` a margin of `15px 0;`

**Comment by iHelpers** [comment]
Using SW 3.3.91 on Safari 12.0.1 OSX 10.14.1 renders my (legacy) editor broken.
Page becomes intermittently unresponsive, the SW Metabox wont open/does nothing when clicking the dropdown arrow, and the Screen Options drop-down arrow also stops working.

Using Firefox 63.0.1 the SW Meta Box will open, but the Screen Options drop-down does not work.
