### ISSUE TITLE
Wishlist/Roadmap

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#392]
**Global Functionality**
- [ ] AMP mobile pages support (#470)
- [ ] share via SMS
- [ ] share via FB Messenger
- [ ] system status: list which tweet count provider is selected in the settings
- [x] Toggle to disable OG output (#436)
  - [x] Toggle to disable OG defaults to Yoast (Iref 17009)
- [x] system status: include legacy vs. advanced and above OG tags on/off (#438) 
- [x] When using shortcode or function, pass in a URL to share rather than a page ID.

**Style**
- [ ] round and square button styles (#439) 
- [ ] color picker for Click to Tweet
- [ ] ability to set a container width for the static buttons and separately for the floating bar within the settings
- [ ] option to show just the icons without buttons/background
- [x] Custom CSS for Click to Tweet? #364 - allow custom input of CSS right inside options page
- [x] resize options for side floating buttons (#453)

**Display / Location**
- [ ] separate mobile options (choose screen size where mobile starts, select new buttons, select new style, etc.)
- [x] floating top option for mobile (not just bottom or off) (#442)
- [x] ability to set the location of the left floating buttons (middle, top, bottom) (#444)
- [x] right floating buttons (#443)
- [x] ability to hide buttons between a "more" type button
- [x] ability to set a different style for buttons called via the shortcode (#471)
- [x] separate styles for static vs. floating
- [x] ability to hide floating buttons above the fold (e.g. post features a cover photo) (#472)

**Analytics** 
- [ ] Adobe Analytics & CID Paramters (IREF 255696)
- [x] Update Click Events to work with GTM (#452)

**Pinterest**
- [ ] Add option for enabling/disabling rich pin for the image (IREF 260745). 
- [ ] Add mobile support for hover 'Save' button by using a click handler on mobile-only.
- [ ] Pinterest image issues with AMP #399 - hidden Pinterest issue is visible and _gigantic_ on AMP pages
- [ ] ability to choose single image or choice of all on the page on a per-post basis 
- [ ] Look at Tasty Pins plugin re: integration with Tailwind
- [ ] Add an option for pin-on-hover images to pin the original image size (instead of the image displayed in content). 
- [ ] Allow multiple hidden Pinterest images on the page.
- [x] block Pinterest browser extension from adding its own Share buttons to images (similar to framebuster - there has to be an attribute we could add to all images that would prevent this) - screenshots iref 12129 (#473)
- [x] Add data-pin-description="" to all images in the post content (#441)
- [x] ~~choice between actual image hovered over or long pin image for Pinterest hover button~~ 
- [x] Make the Pinit Hover button ignore hidden images (#400) 
- [x] Translate image hover "Share" text
- [x] Disable Pinit Button for Image Links / New Pinit Button Display Options (#405)

**Yummly**
- [ ] Add featured image as fallback option if there is no custom image set
- [ ] Yummly replacement button: If Yummly is only used on one category, add an option to replace the Yummly button with something else on other categories. 
- [ ] Ability to enter a comma-separated list of categories or tags to show the Yummly share button instead of just a single category or tag.

**Twitter**
- [ ] Allow choice of "go to beginning of article" or "use CTT as an anchor to take people straight to the CTT part of the article" in the Click to Tweet shortcode.
- [x] Separate Twitter Image (instead of having it use the Social Media Image)

**Bitly**
 - [x] Allow custom branded Bitly URLs. 

**WhatsApp**
 - [x] Make the button work on desktop. 

**Email Share**
- [ ] customize the email text on a per-post basis as well as a global default

**Widgets**
- [ ] Follow widget: make sure iTunes, Stitcher, Soundcloud, and Google Play buttons are included (I think we're going to break this out into an addon)
- [ ] popular posts widget: ability to choose from theme image sizes instead of manually adding height and width
- [ ] popular posts widget: ability to filter by language (for WPML sites)
- [ ] popular posts widget: ability to exclude categories/tags or to include only posts from a single category/tag
- [ ] Click to Tweet widget
- [ ] popular posts widget: when featured image is a video, allow video thumbnail/overlay to be shown (iref 15806)
- [x] popular posts widget: allow CPTs (checkbox per CPT to include?)
- [x] popular posts widget options for (1) Vertical and Horizontal thumbnail dimensions and (2) Crop or scale image

**Device Compatability**
 - [ ] The Pin button (in socialPanel) does not work on iPhone 6. Other buttons are fine. 

**Data Collection**
- [ ] Use Google Analytics to watch share counts and gather stats for client
- [ ] Client agrees to share their data with SWP for our own aggregation 

**Newly Added Wishlist Items / Items Needing Review, Consideration & Planning**

**Add-ons:**
- [ ] [Post Affiliate Pro](https://www.postaffiliatepro.com/) integration just like AffWP

**General**
- [x] Add tooltips to each social network button in Social Warfare > Display > Social Networks because some people have no idea what the more obscure ones are, and the email icon is so hard to see, people complain about not realizing what it is.

**Comment by Nicholas-Cardot** [comment]
1. Google Event Tracking 
We're wondering if it's possible to modify the 'eventCategory' from 'outbound-article' to something else?

2. UTM Link Tracking 
We're wondering if it's possible to include and customize the utm_content parameter? This may be slightly more complicated since this value would need to be customized on a per post basis, ideally.

**Comment by ckmahoney** [comment]
Notes for writing a documentation: 

IR #16308
Let users know that Bitly links only work on public facing sites.

**Comment by ckmahoney** [comment]
Notes for translations: 

**French**
IR #16381

For the user profile:

social-warfare\functions\admin\profile-fields.php

Line 18:

echo '<h3>__( 'Social Warfare Fields', 'social-warfare')</h3>';

For the system information:

social-warfare\functions\admin\options-page.php

Line 782 to line 796

<tr><td><h2>__( 'Environment Statuses', 'social-warfare')</h2></td><td></td></tr>

<tr><td><b>__( 'Home URL', 'social-warfare')</b></td><td>' . get_home_url() . '</td></tr>

<tr><td><b>__( 'Site URL', 'social-warfare')</b></td><td>' . get_site_url() . '</td></tr>

<tr><td><b>__( 'WordPress Version', 'social-warfare')</b></td><td>' . get_bloginfo( 'version' ) . '</td></tr>

<tr><td><b>__( 'PHP Version', 'social-warfare')</b></td><td>' . phpversion() . '</td></tr>

<tr><td><b>__( 'WP Memory Limit', 'social-warfare')</b></td><td>' . WP_MEMORY_LIMIT . '</td></tr>

<tr><td><b>__( 'Social Warfare Version', 'social-warfare')</b></td><td>' . SWP_VERSION . '</td></tr>

<tr><td><h2>__( 'Connection Statuses', 'social-warfare')</h2></td><td></td></tr>

<tr><td><b>__( 'fsockopen', 'social-warfare')</b></td><td>' . $fsockopen . '</td></tr>

<tr><td><b>__( 'cURL', 'social-warfare')</b></td><td>' . $curl_status . '</td></tr>

<tr><td><h2>__( 'Plugin Statuses', 'social-warfare')</h2></td><td></td></tr>

<tr><td><b>__( 'Theme Name', 'social-warfare')/b></td><td>' . $theme['Name'] . '</td></tr>

<tr><td><b>__( 'Theme Version', 'social-warfare')</b></td><td>' . $theme['Version'] . '</td></tr>

<tr><td><b>__( 'Active Plugins', 'social-warfare')</b></td><td></td></tr>

<tr><td><b>__( 'Number of Active Plugins', 'social-warfare')</b></td><td>' . count( $plugins ) . '</td></tr>

For the widget:

social-warfare\functions\widgets\widgets.php

Line 10:

parent::__construct( false, $name = __( 'Social Warfare: Popular Posts', 'social-warfare' );

Between line 76 and line 198, words are not translated

For the WordPress text editor:

In the last two files, words are not translated:

C:\Users\guill\Downloads\social-warfare\functions\click-to-tweet\assets\js\clickToTweet.js

C:\Users\guill\Downloads\social-warfare\js\sw-shortcode-generator.js

**Comment by ckmahoney** [comment]
Added "WhatsApp: Make the button work on desktop."

**Comment by ckmahoney** [comment]
added 
Pinterst > Add option for enabling/disabling rich pin for the image (IREF 260745).
