### ISSUE TITLE
3.1.0 Fix List

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#550]
This is a living list of bugs which will be resolved for the 3.1.0 release. Please place feature requests in a new issue. Discussion of items on this list can be carried on in threads here. 

For larger scope items, such as new classes or changes in mechanics, we can create a new issue. 

**`TODO`**
- [x] Share counts still do not update. 
- [x] Popular Posts Widget is still not updating (probably related to share counts)
- [x] Outbound cURL requests still happen more than one time. 
- [x] Some sites do not have the settings saving. (IREF 19172)
- [x] Ability to correctly define button placement on homepage, be it blog or static. 
- [x] AffiliateWP registration does not display in the Registration tab. 
- [ ] Totals option does not work in shortcode.
- [ ] JS: 'socialwarWarfarePlugin is undefined' line 283 of admin-options-page.js (TicketID 172394)
- [x] Pin Images do not display correctly. Often missing images from the post. 
- [ ] CTT adds an extra social panel above the social panel. (Fringe, IREF 19396)
- [x] Pin image hover is assigning description correctly, but main Pinterest button is using the image alt text instead of the description. Ask Andrea for a URL to see this issue (iref 174015 in the new system). UPDATE (TicketID 174936) The problem exists at utility.php L123, L132 in $pinterest_description.
- [ ] Font css not being output. (Similar to above, issue lies in SWP_Pro_Header_Output)
- [ ] [Awesome Support conflict] Shortcode is firing in admin on the editor, outputting HTML. (TicketID 173658)

**`Edge`**
 - [x] The first button in a left/right side floating panel displays no text and does nothing on click.
**`Done`**
- [x] Top floating bar appears before buttons_panel appears, should wait until buttons_panel has been visible.
- [x] PHP notice on image attachment pages `Undefined index: location_attachment in /www/wp-content/plugins/social-warfare/functions/frontend-output/SWP_Buttons_Panel.php on line 298`
- [x] Page id does not work in the shortcode. 
- [x] Twitter meta tags are not being output. 
- [x] Update references of `http://` to `https://` where possible (e.g. Facebook links)
 - [x] Add 'rel="noopener"' or 'rel="noreferrer"' to links. (IREF 18785)

**Comment by Nicholas-Cardot** [comment]
If any items on this checklist do pop back up in a future bug report, we will use individual GitHub issues to track them to their conclusions.
