### ISSUE TITLE
Create SWP_Cache and SWP_Post_Cache classes. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#553]
Our caching mechanism is in dire need of an overhaul to better fit in with our new framework. After some discussion, we have decided these are the required features: 

1. A globally accessible container of all post cache data. This will be the SWP_Cache object.
2. Individual SWP_Post_Cache objects to control their own caching and fetching. 
3. Methods to asynchronously fetch share count data on the server while still delivering content. 
    - There is a third party class which can help us with this. 
4. Hooks for network classes to filter the post meta. 

The proceeding comment holds the living sketches for these two classes.

**`TODO`**

- [x] Create and outline SWP_Cache.
- [x] Flesh out SWP_Cache.
- [x] Create and outline SWP_Post_Cache.
- [x] Flesh out SWP_Post_Cache.
- [x] Investigate this third party resource: https://github.com/A5hleyRich/wp-background-processing. 
- [x] Create hooks for social networks to access SWP_Post_Cache.
- [x] Research IP spoofing for Facebook API requests.

**Comment by ckmahoney** [comment]
```
class SWP_Cache {
    /**
    * Array of the currently loaded SWP_Post_Cache objects, indexed by post_id.
    * These are meant to be accessed by the Buttons Panel, for example. 
    * 
    */
    public $post_caches = array();

    public function get_post_cache( $post_id ) {
        if ( array_key_exists( $post_id, $this->post_caches ) :
            return $this->post_caches[$post_id];
        endif;

        $post_cache = new SWP_Post_Cache( $post_id );
        $this->post_caches[$post_id] = $post_cache;
        
        return $post_cache;
    }
}

class SWP_Post_Cache {
    /**
     * @var bool $fresh_cache
     *
     * True if the post has recently been updated, false otherwise. 
     */
    public $fresh_cache = false;
    
    __construct( $post_id ) {
        global $post;

        if ( $post->ID != $post_id ) {
            $post = get_post( $post_id );
        }

        $this->post_id = $post_id;
        $this->post = $post;
        $this->fresh_cache = $this->has_fresh_cache();
    }

    /**
     * Determines if the data has recently been updated.
     * 
     * @access protected Use the $fresh_cache property to determine cache status.
     * @return bool true if the cache has recently been updated, else false. 
     *
     */
    protected function has_fresh_cache() {
        //* Do checks based on publish date. 
    }

    /**
     * Get either the cached or updated post meta. 
     * 
     * @return mixed $meta An array of post_meta, or void if not found. 
     *
     */
    public function get_post_meta() {
        if ( $this->fresh_cache ) :
            return get_post_meta( $this->id );
        endif;

        //* Cache is not fresh. Do the requests. 
        $data = do_requests();

        if ( !$data ) {
          //* Output the ajax JS.
          return; 
        }
        
        $meta = cleanup_data($data);
        
        update_post_meta( $this->id, $meta );
        $this->post->post_meta = $meta;
        
        return $meta;
    }
}
```

**Comment by Nicholas-Cardot** [comment]
This class will primarily take care of 3 things:
1. Determine if the cache is fresh or not.
2. Rebuild the cache if it is not fresh.
3. Provide access to the cached data.

I think #1 is pretty much completely solved. After reviewing, you should be able to confirm or deny that.

Everything related to #1 and #2 should be private/protected methods just like you've been doing so far. Stuff related to #3, should obviously be publicly accessible.
In fact, the only thing in #3, I think, will probably be a method to fetch cached share counts.
The share count method, we'll break into two methods. The public one will ONLY fetch cached share counts. The private one will ONLY fetch share counts from the API to rebuild the cached counts.

**Comment by Nicholas-Cardot** [comment]
This is being closed as it is now complete pending testing.
