### ISSUE TITLE
3.1.0 Beta Testing Checklist of Bugs and Findings

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#565]
### Unsolved
- [x] **Plugin is adding unnecessary padding to `body` element of posts**. Conditions are (a) global float setting for that post type must be OFF, and (b) bottom/top floating buttons are not active in that single post.

### Andrea's bugs

- [x] Total shares shortcode broke in a very spectacular fashion. This will affect some of our customers since we used to give out the function to create the shortcode - it took my site down the second I installed 3.1.0.
```[Fri Jul 06 22:08:35.272419 2018] [proxy_fcgi:error] [pid 22017] [client 127.0.0.1:50701] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function swp_kilomega() in /home/138698.cloudwaysapps.com/xpkxzdbjeq/public_html/wp-content/themes/nabm/includes/theme-functions.php:158\nStack trace:\n#0```
- [x] Once I resolved the above, my site is still borked because of this error:
```Fri Jul 06 22:17:23.745358 2018] [proxy_fcgi:error] [pid 22681] [client 127.0.0.1:54518] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function swp_is_cache_fresh() in /home/138698.cloudwaysapps.com/xpkxzdbjeq/public_html/wp-content/plugins/social-warfare/functions/utilities/SWP_URL_Management.php:185\nStack trace:\n#0 /```

---------------------

- [x] side-floating fade in/out blinking again. 
Note: I'm checking this item off for two reason. First, it is being tracked as it's own issue. Second, thus far, we have looked into it multiple times and have yet to be able to determine any ideas as to what we might be able to do in order to fix it. This means that this specific item will not be able to be completed prior to the launch of 3.1. We are therefore classifying it as a "known issue" and tagging it for development for the 3.2.0 milestone. This issue can be viewed here: https://github.com/warfare-plugins/social-warfare/issues/539

- [x] side-floating share icon is above counts (should be inline)
- [x] side-floating buttons still showing on mobile (alongside top/bottom floating)
- [x] bottom-floating buttons slow to appear/disappear on emailcrash.com (fade in/out) - sometimes they don't show up at all
- [x] bottom-floating on mobile flashes during scroll (make sure these only use show/hide)
- [x] pinterest description box is missing
- [x] change wording on single post share recover from "pattern" to "permalink"
- [x] stumbleupon notice dismiss button opens up a new blank tab
- [x] no control over transition for bottom/top floating buttons
[duplicate] side-floating buttons seem buggy for in/out transitions
- [x] shortcode not loading on homepage at willcallband.com

**Comment by DustinWStout** [comment]
Added new item for excess padding issue.

**Comment by Nicholas-Cardot** [comment]
This issue is now closed. A new issue will be creating during the beta testing period for our next update.
