### ISSUE TITLE
3.1.x Bugfix Checklist

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#570]
**Current Issues**

Nothing here...yet.

**The Following Issues Are Complete and Included in 3.1.1**
- [x] 1. `Uncaught ReferenceError: minWidth is not defined` coming from line 101 if script.min.js is unminified
- [x] 2. The shortcode shows ALL share buttons if you don’t specify which buttons to show.
- [x] 3. One person's floating buttons aren’t showing on mobile. (TicketID 183856)
- [x] 4. floatbeforecontent variable is being output multiple times in the footer. Simply migrate the method and the associated hook from Buttons_Panel class to Script class.
- [x] 5. Undefined index: post_id in /home/ketovale/public_html/wp-content/plugins/social-warfare/functions/utilities/SWP_Post_Cache_Loader.php on line 113

**Comment by Nicholas-Cardot** [comment]
It is very, very highly likely that item 3 was being caused by item 1. We need to find that site where it wasn't working and install our fixed version in order to confirm this.

**Comment by ckmahoney** [comment]
I have requested logins from the ticket that reported the issue.
