### ISSUE TITLE
3.2.0 Beta Testing Bugs & Glitches Checklist

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#582]
# Schedule
**Private Beta Testing: July 27 through August 3**
**Public Beta Testing: August 3 through August 10**
The beta testing period for version 3.2.0 will open on **Friday, August 3 at 5:00 PM**. When the development team goes home for the day on that Friday, we will ensure that the code on the testing branch is fully ready for beta testing. 

The testing period is scheduled to remain open until the following **Friday, August 10, 2018** with the hope of releasing version 3.2.0 on **Monday, August 13th at or around 10:00 AM**.

To follow and track our development schedule, please check the following calendar: https://calendar.google.com/calendar?cid=c2l0ZXNrZXRjaDEwMS5jb21fb3RrOHJyb2FwNnE1ZHBxc2pxMGc4YWVhYmdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

# Guidance

### Up-to-date plugin bundles. Clean & ready for install.

[social-warfare.zip](https://github.com/warfare-plugins/social-warfare/files/2271092/social-warfare.zip)
Core last updated August 8, 2018.

[social-warfare-pro.zip](https://github.com/warfare-plugins/social-warfare/files/2275495/social-warfare-pro.zip)
Pro last updated August 9, 2018.
 
These are the main issues we are targeting for this update: 
https://github.com/warfare-plugins/social-warfare/milestone/4

Every issue marked as "Ready for Testing" is ready for testing. When you click the issue title, it will take you to description of what has been going on. We have provided notes on what we expect to happen, and how to test whether or not that happens. 

If you go through the processes and something doesn't seem right, you can reply to that issue as a comment. 

# THE CHECKLIST
Any bugs or glitches that you find, **please post them in the corresponding issue, or in the comments below**. We will aggregate them into this issue in the form of this checklist and work quickly to get them resolved.

- [x] ncaught TypeError: Cannot read property 'left' of undefined in Script.js on line 255. Context: The buttons panel doesn't exist on the page so any calls to it's properties will throw an error.
- [x] Make the CTA's on the notices open in the existing tab with an optional parameter that can cause it to open in a new tab.
- [x] Boxes and Circles in the side floating buttons have the height broken on them. They appear vertically smooshed. 
- [x] Version mismatch stops the update checker from running.
- [x] Fix the dropdown to remove newsharecounts and add Twitcount.
- [x] Double floating buttons (see below)

**Comment by DustinWStout** [comment]
Something happened to the "Boxes" style for side-floating buttons. 

<img width="251" alt="screen shot 2018-07-27 at 10 30 17 am" src="https://user-images.githubusercontent.com/2152604/43337241-1de2ccfc-9188-11e8-967b-61cf9a0d9fcf.png">

**Comment by DustinWStout** [comment]
Circles too...

<img width="127" alt="screen shot 2018-07-27 at 10 32 22 am" src="https://user-images.githubusercontent.com/2152604/43337317-5ffa0e3e-9188-11e8-940a-ee28406bfd70.png">

**Comment by DustinWStout** [comment]
If a user has previously made changes to styling that are only available in Pro, but they downgrade to only Core, their styles **should** revert to a standard style. Instead, this is what happens (no styling): 

<img width="865" alt="screen shot 2018-07-27 at 10 40 04 am" src="https://user-images.githubusercontent.com/2152604/43337766-9442d79c-9189-11e8-982d-32a86d0de638.png">

We've seen many support tickets come in about this, and while it's easy to explain, would save us a TON of time in support if the plugin just reverted to default styles.

**Comment by Nicholas-Cardot** [comment]
@DustinWStout Regarding the settings not reverting properly. In order to fix this, we're going to have to create a whole new mechanism for handling this properly and make it in a way that it will handle settings from future addons as well. So while I agree that it needs done, that amount of changes to the code wouldn't be safe to make in the middle of a beta testing cycle. So I'm going to make this it's own issue and make it a very high priority for 3.3.0. This way it will be fully realized and testable prior to the beta testing cycles for that version.

**Comment by ckmahoney** [comment]
@Nicholas-Cardot Notes on the first item, the JS uncaught TypeError:

This same error has been produced in a few different instances since 3.1.0. Each time it comes down to an `.swp_social_panel:not(swp_social_panelSide):not(nc_floater)` (a regular buttons panel) not being present on the page. 

Formerly floaters required the horizontal buttons because the panel held data that the floaters needed. Now floaters have the exact same `data-x` attributes, so our script.js has changed a bit accordingly. The floaters can read their own data attributes.

Now top/bottom floaters only require a set of horizontal buttons so they can be placed properly on the page. But the admin does not always want horizontal buttons displayed and sometimes just wants the floating buttons. 

In the future, I would like to see floaters entirely separate from horizontal buttons. Any set of buttons should be able to exist independent of any other set of buttons. 

Right now the fix was:
```
If horizontal buttons are off && using top/bottom floating buttons
  create a set of horizontal buttons and give it an opacity 0. 
```

**Comment by Nicholas-Cardot** [comment]
@DustinWStout The updater issues should now be fully resolved. Please grab the copy from the testing branch as we haven't rezipped it just yet. This was a change in pro, not core.

**Comment by DustinWStout** [comment]
@Nicholas-Cardot downloaded, installed, and tested the versions in the testing branch... no change in behavior.

**Comment by Nicholas-Cardot** [comment]
We forgot to push it up to the testing branch. Please stand by.

**Comment by joetracy** [comment]
Issue: Double Floater
Wordpress: 4.98
Link to Issue: https://writingbooks.newsdial.com/index.php/2015/07/22/hello-world/
See Attached Image
![doublefloaters](https://user-images.githubusercontent.com/41494575/43730587-aa464acc-9960-11e8-868e-950205b9630b.jpg)

**Comment by ckmahoney** [comment]
Hi @joetracy, I've just applied the patch that fixes the double floating bar. Please feel free to download the updated zip!

**Comment by DustinWStout** [comment]
@ckmahoney button click tracking is working for all buttons **except the Email button**.

**Comment by meymigrou** [comment]
I found a pretty funny bug in the 3.2 beta. After installing it, all my blog posts that are written in Greek have been changed. It's like the font won't support the Greek letters anymore or something like that. If I disable the Social Warfare Pro, the font automatically fixes. If I enable it again, I'm getting the same problem.
![social-warfare-bug](https://user-images.githubusercontent.com/30810726/43917198-461dba20-9c18-11e8-92a7-0a41e1d3ebe5.png)

**Comment by JasonWiser** [comment]
I cannot get "Button Shape" -> "Pills" to work. 
it is the same style as "Flat and Fresh" 
both on the frontend and in the dashboard. 

When I use the dropdown selector for Styles -> "Button Shape" all others work perfectly except pills

**Comment by JasonWiser** [comment]
Just FYI - (and maybe everyone knows this already) 
When you visit my site using http the button icons are broken 
![2018-08-10_105707](https://user-images.githubusercontent.com/18461953/43965034-2c933354-9c8c-11e8-92eb-489923fae692.jpg)
 but when it is https:// it works. 

I know what I need to do to fix this, just FYI

**Comment by meymigrou** [comment]
@JasonWiser the problem doesn't only occur to Social Warfare, many plugins and even themes have the same problem when giving the ability to users to either visit your website as http:// or https:// - something that is absolutely absurd. There's no benefit having both http:// and https:// enabled, only problems.
