### ISSUE TITLE
3.4.x Buglist Checklist

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#676]
So far the bugs reported in 3.4.0 are very minor. As such, we'll simply use this issue to track anything that gets reported. If there are numerous bugs or any that are severe, then we will break this list into their own separate issues.

**Current Testable Beta Versions**
The following attachments are the most current version of the plugin. As such, it can be tested against any of the issues that have been checked off below to confirm these patches:

All current zips are currently published.

**Fixed in Version 3.4.2: Released Thursday, 13 DEC 2018**

- [x] (Soft Updated) When theme is set to default, the CTT does not output the global theme when CTT is added via Gutenberg blocks.
- [x] (Soft Updated) Left/right floating buttons have disappeared.
- [x] (Soft Updated) Facebook shares need typechecking
- [x] In some cases, floating button width is incorrect.
- [x] Floating bottom disappear on mobile when pro is deactivated (IREF 244278).
- [x] Blocks no longer show up on Gutenberg on WP 5.0
- [x] In some instances, pages are being switch from 'default' to 'on' for Floating location. (IREF 248474)
- [x] Floating positions are wonky on the home page when the page uses a page template (not a blogroll, not a WP page).
- [x] Buttons panel showing up on post types where buttons are turned off if the page uses a content builder that passes empty content into the_content filter.
- [x] The content-locator div is not being output for use by the float_before_content function unless the pinit_toggle is turned on.

**Fixed in Version 3.4.1: Released Wednesday, 5 DEC 2018**

- [x] Twitter card toggle not working as expected in post meta.
- [x] Update the directions for the share count sources
- [x] Fix the error when dynamic sorting is selected and no share counts are present.
- [x] WhatsApp popup leads to a 404 on the customer site instead of opening WhatsApp web - ticket sent to dev box
- [x] Float before content is not working. 
- [x] Mobile floating buttons are off screen.
- [x] Admin js error: `socialWarfare.activateHoverStates is not a function`
- [x] Admin js error: `$ is not a function`
- [x] Remove Open Share Count signup button and references to Open Share Count on the social identity screen in the settings
- [x] Character counter for Pinterest descriptions is the wrong number.
- [x] Uncaught TypeError: Cannot read property ‘css’ of null at socialWarfare.updateFloatingHorizontalDimensions
- [x] Resizing from desktop to mobile when desktop: left and mobile: bottom, floaters break.
- [x] Email button is borked

**Comment by ckmahoney** [comment]
- Float Before Content does not work anymore. 
   - Fixed in PHP https://github.com/warfare-plugins/social-warfare/commit/b539a6569e1083ba498edd869ba9118b5eb91cfe and JS https://github.com/warfare-plugins/social-warfare/commit/002de06bf7ef49b048f739996b23f8b62ec5b7de

**Comment by ckmahoney** [comment]
- Floating Bar placement is off-center on mobile

**Comment by Nicholas-Cardot** [comment]
Will that CSS break that alignment on non-mobile? If it's not full width, that will stick it to the left instead of putting the left as what the JS calculates it to be.

**Comment by ckmahoney** [comment]
**Admin JS error: `socialWarfare.activateHoverStates is not a function`**

**Comment by ckmahoney** [comment]
IREF 244909

**Admin JS Error:** `$ is not a function` L 181

**Comment by ckmahoney** [comment]
IREF 244278

**Pinterest Character Limit needs to be 500**

**Comment by ckmahoney** [comment]
IREF 

**The WhatsApp button** is not generating a WhatsApp protocol whatsoever. 

This is the link in the anchor tag on desktop: 
> https%3A%2F%2Fmariasmenu.com%2Fsalads%2Fchopped-tuna-salad%3Futm_source%3Dwhatsapp%26utm_medium%3Dsocial%26utm_campaign%3Dbuttons

This is the link in the anchor tag on FireFox mobile Android:
> https://mariasmenu.com/salads/https%3A%2F%2Fmariasmenu.com%2Fsalads%2Fchopped-tuna-salad%3Futm_source%3Dwhatsapp%26utm_medium%3Dsocial%26utm_campaign%3Dbuttons

**Comment by mkasu** [comment]
> Will that CSS break that alignment on non-mobile? If it's not full width, that will stick it to the left instead of putting the left as what the JS calculates it to be.

I can confirm that the CSS breaks alignment on non-mobile.

**Comment by Nicholas-Cardot** [comment]
That's correct. We moved away from using that CSS and updated the JS to calculate it properly. The version on the 3.4 development branch here is ready to test with the new JS if you'd like to take it for a spin.

**Comment by ckmahoney** [comment]
`mailto:` **link in Email button is broken**

 - [ ] The body is not being passed in the message.

**Comment by brevstgaard** [comment]
Am I the only one that has the problem, that when I have activated "Floating Share Buttons" but choose mobile "Off" on mobile have a mobile top-menu/heaer menu that dosen't work? I mean so the menu press isn't giving the menu? - No floating is set to top or bottom everything is working fine but when off, something breaks somewere and also working perfectly with the plugin deactivated?

I'm still on version 3.4.1 + Pro for now by the way, if any help.

Thanks.

**Comment by ckmahoney** [comment]
Good morning @brevstgaard,

We have a few reports of the mobile menus not working with version 3.4.x of Social Warfare. 
We have not yet determined the cause. So far we haven't seen any errors in the console, which is most often the reason why things don't work as we expect them to.

Can you please provide a link to where we can view the issue on your site? That would be very helpful for me while debugging.

**Comment by ckmahoney** [comment]
Actually @brevstgaard, our developer @Nicholas-Cardot may have already patched this bug and pushed it as a soft update to 3.4.1.

This means that the version number is the same, but the code is different now for 3.4.1 compared to when you downloaded it. 
Please try deactivating Core (and Pro if you have it), uninstalling just Core, and then reinstalling fresh from the WordPress plugin repository. 

I hope this works for you.
- Cortland

**Comment by brevstgaard** [comment]
@ckmahoney its working again so thanks! - Removed the free plugin and installed it again from the repository, cache cleared and now back in action.
