### ISSUE TITLE
[New] Add the Vkontakte social network.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#739]
### Research
The following research is needed in order to create a new sharing button in our system:
- [x] Research: Find share URL 
- [x] Research: Find and integrate the Call to Action verb.
- [x] Research: Find and integrate share count API endpoint URL 
- [x] Research: Identify the color for the network brand. 

### Information Gathered
The following information is to be gathered during the research phase above and can therefore be used during the integration phase below:
- **Share URL:** http://vk.com/share.php?url=
- **Brand Color:** #4a76a8
- **Icon Content:** NEEDED
- **Call To Action Verb:** Share
- **API Endpoint URL:** https://vk.com/share.php?act=count&url=

### Tasks
The following are the steps needed to be taken in order to integrate this new network into our system:
- [x] Create the network file (The PHP File). 
- [x] Add the color code and icon content to variables.scss (The CSS)
- [x] Add an icon to the icon font.

**Comment by Nicholas-Cardot** [comment]
This is now ready for testing.

**Comment by Nicholas-Cardot** [comment]
This network has been added and appears to be fully functional. However, we now need to have the icon added to the icon font. Then this will all be wrapped up and ready to go.

**Comment by Nicholas-Cardot** [comment]
### 🔎 Testing Guidance 🧪

1. Go to the admin options page for Social Warfare.
2. Navigate to the "Display" tab and look for the "Social Networks" section.
3. Drag the button to the "Active" section. 
4. Load a post on the frontend. 
5. Attempt to share the post to this social network. 

Did the button display properly in the buttons panel on the post? Did the share work properly?

Report back in the comments below whether it worked properly or not. Report on what you encounter.
