### ISSUE TITLE
[New] Add a Digg share button.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#744]
### Research
The following research is needed in order to create a new sharing button in our system:
- [x] Research: Find share URL 
- [x] Research: Find and integrate the Call to Action verb.
- [x] Research: Find and integrate share count API endpoint URL 
- [x] Research: Identify the color for the network brand. 

### Information Gathered
The following information is to be gathered during the research phase above and can therefore be used during the integration phase below:
- **Share URL:** http://digg.com/submit?url={url}
- **Brand Color:** #005be2 
- **Icon Content:** 
- **Call To Action Verb:** Digg
- **API Endpoint URL:** Void

### Tasks
The following are the steps needed to be taken in order to integrate this new network into our system:
- [ ] Create the network file (The PHP File). 
- [ ] Add the color code and icon content to variables.scss (The CSS)
- [ ] Add an icon to the icon font.

**Comment by Nicholas-Cardot** [comment]
This share button may be obsolete.

**Comment by Nicholas-Cardot** [comment]
Dustin, can you find out if this is still a valid share link? Or what's going on with this network?
